#!/bin/bash -xe 

sudo apt install libsdl2-dev -y
sudo apt install libsdl2-image-dev -y
sudo apt install libsdl2-mixer-dev -y
sudo apt-get install libboost-all-dev -y
sudo apt-get install libavcodec-dev -y
sudo apt install libmnl-dev -y

autoconf
./configure
make


