#!/bin/bash -xe 


OS=$(uname -s)


LDF=""
INC=""
function getlib
{
  X=$(find /opt/homebrew/Cellar/ -name "$1.*" | tail -1)
  [ -z "$X" ] ||  { 
     D=$(dirname "$X")
     LDF="$LDF -L$D"
     R=$(dirname "$D")
     R="$R/include"
     INC="$INC -I$R"
  }
}

function addinc
{
  X=$(find /opt/homebrew/Cellar -name "$1" | tail -1)
  [ -z "$X" ] || {
    D=$(dirname "$X")
    INC="$INC -I$D"
  }
}

FRAMEWORKS=""

if [ "$OS" = "Linux" ] ; then
  sudo apt install libsdl2-dev -y
  sudo apt install libsdl2-image-dev -y
  sudo apt install libsdl2-mixer-dev -y
  sudo apt-get install libboost-all-dev -y
  sudo apt-get install libavcodec-dev -y
  sudo apt install libmnl-dev -y
fi

if [ "$OS" = "Darwin" ] ; then
   brew install sdl2 sdl2_image sdl2_mixer sdl2_sound sdl2_gfx sdl2_ttf
   getlib libSDL2
   getlib libSDL2_image
   getlib libSDL2_mixer
   getlib libSDL2_sound
   getlib libSDL2_gfx
   getlib libSDL2_ttf
   addinc SDL.h


   [ -d "$HOME/build" ] || mkdir -p "$HOME/build"
   cd "$HOME/build"

   [ -d "$HOME/libav/lib" ] || {
      curl -kv https://libav.org/releases/libav-12.3.tar.gz -o libav-12.3.tar.gz
      tar xzvf libav-12.3.tar.gz
      cd libav-12.3
      ./configure --prefix=$HOME/libav
       make
       make install
   }
   cd -
   LDF="$LDF -L$HOME/libav/lib"
   INC="$INC -I$HOME/libav/include"
   FRAMEWORKS="-framework CoreFoundation -framework CoreVideo -framework VideoDecodeAcceleration"
fi






#autoconf
./configure LDFLAGS="$LDF $FRAMEWORKS" CFLAGS="$INC"
#make


